### ISSUE TITLE
too homosexual

### ISSUE THREAD

**Issue by Cyclcrclicly** [Aktimoose/nickel#1]
turn down the homosexuality a bit please

**Comment by Cyclcrclicly** [comment]
Has this been resolved yet?

**Comment by Cyclcrclicly** [comment]
Has this been resolved yet?

**Comment by Cyclcrclicly** [comment]
Has this been resolved yet?

**Comment by Cyclcrclicly** [comment]
Has this been resolved yet?

**Comment by Cyclcrclicly** [comment]
dang i guess it has not been resolved yet

**Comment by Cyclcrclicly** [comment]
fuck ing whore

**Comment by Kyza** [comment]
Cannot reproduce the issue.

**Comment by lyndseyy** [comment]
Fixed upstream in Commit #284f72d

**Comment by Aktimoose** [comment]
Cannot recreate issue.

**Comment by Kyza** [comment]
Has this been resolved yet?

**Comment by Aktimoose** [comment]
Cannot recreate issue.
